"""initial schema

Revision: 0001  (follows )
Created: 2026-10-08 19:17:26.297441"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None

ROLES = {
    "user": "A learner",
    "staff": "Can see users and learning data to help them",
    "editor": "Can edit courses, lessons and knowledge",
    "moderator": "Can review and act on user content",
    "admin": "Can manage users, invites, content and configuration",
    "super_admin": "Everything, including roles and system configuration",
}
PERMISSIONS = {
    "users.read": "See users and their profiles",
    "users.update": "Change a user's profile or status",
    "users.suspend": "Suspend or reactivate an account",
    "users.delete": "Delete an account and its data",
    "roles.assign": "Give or take a role",
    "invites.manage": "Add or remove invitations",
    "learning.read": "See learning progress (support)",
    "content.edit": "Edit courses, lessons and knowledge",
    "insights.read": "See the product's numbers",
    "ai.config.edit": "Change AI models, prompts and limits",
    "system.config.edit": "Change system configuration",
    "audit.read": "Read the audit log",
}
GRANTS = {
    "staff": ["users.read", "learning.read"],
    "editor": ["content.edit"],
    "moderator": ["users.read", "users.suspend"],
    "admin": ["users.read", "users.update", "users.suspend", "invites.manage", "learning.read", "content.edit",
              "insights.read", "audit.read"],
    "super_admin": sorted(PERMISSIONS),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_permissions'))
    )
    op.create_table('roles',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('builtin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_roles'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legacy_id', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), server_default='', nullable=False),
    sa.Column('avatar_url', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('active', 'suspended', 'deleted')", name=op.f('ck_users_status')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lower')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('legacy_id', name=op.f('uq_users_legacy_id'))
    )
    op.create_table('ai_usage',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('token_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_usage_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day', name=op.f('pk_ai_usage'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=True),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_at', 'audit_log', ['at'], unique=False)
    op.create_table('credentials',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("algorithm in ('argon2id', 'bcrypt')", name=op.f('ck_credentials_algorithm')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_credentials_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_credentials'))
    )
    op.create_table('day_lessons',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('lesson_no', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('unit', sa.Text(), server_default='', nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('from_day', sa.Date(), nullable=True),
    sa.Column('passed_on', sa.Date(), nullable=True),
    sa.Column('tracks_cards', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tracks_evidence', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_day_lessons_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_day_lessons')),
    sa.UniqueConstraint('user_id', 'day', 'subject', 'lesson_no', name=op.f('uq_day_lessons_user_id_day_subject_lesson_no'))
    )
    op.create_index('ix_day_lessons_user_id_subject_lesson_no', 'day_lessons', ['user_id', 'subject', 'lesson_no'], unique=False)
    op.create_table('goals',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'id', name=op.f('pk_goals'))
    )
    op.create_table('identities',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_identities_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identities')),
    sa.UniqueConstraint('provider', 'subject', name=op.f('uq_identities_provider_subject'))
    )
    op.create_index('ix_identities_user_id', 'identities', ['user_id'], unique=False)
    op.create_table('invites',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('invited_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_invites_email_lower')),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_invites_invited_by'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('email', name=op.f('pk_invites'))
    )
    op.create_table('learning_signals',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_signals_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day', 'event', name=op.f('pk_learning_signals'))
    )
    op.create_table('preferences',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_preferences_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_preferences'))
    )
    op.create_table('reading_books',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reading_books_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'id', name=op.f('pk_reading_books'))
    )
    op.create_table('role_permissions',
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('permission', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['permission'], ['permissions.name'], name=op.f('fk_role_permissions_permission'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role'], ['roles.name'], name=op.f('fk_role_permissions_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role', 'permission', name=op.f('pk_role_permissions'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('study_days',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('level', sa.Text(), server_default='', nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('followup_question', sa.Text(), server_default='', nullable=False),
    sa.Column('reflection', sa.Text(), server_default='', nullable=False),
    sa.Column('legacy_lesson', sa.Text(), server_default='', nullable=False),
    sa.Column('legacy_kickoff', sa.Text(), server_default='', nullable=False),
    sa.Column('legacy_followups', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_study_days_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day', 'subject', name=op.f('pk_study_days'))
    )
    op.create_index('ix_study_days_user_id_subject', 'study_days', ['user_id', 'subject'], unique=False)
    op.create_table('subject_levels',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subject_levels_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subject', name=op.f('pk_subject_levels'))
    )
    op.create_table('usage_events',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_events_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'day', 'event', name=op.f('pk_usage_events'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.name'], name=op.f('fk_user_roles_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role', name=op.f('pk_user_roles'))
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('units_per_day', sa.Integer(), nullable=False),
    sa.Column('reading_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('onboarding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onboarded_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings'))
    )
    op.create_table('user_subjects',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_subjects_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subject', name=op.f('pk_user_subjects'))
    )
    op.create_table('explanations',
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('reply_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['day_lessons.id'], name=op.f('fk_explanations_slot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', name=op.f('pk_explanations'))
    )
    op.create_table('lesson_contents',
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('kickoff', sa.Text(), server_default='', nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['day_lessons.id'], name=op.f('fk_lesson_contents_slot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', name=op.f('pk_lesson_contents'))
    )
    op.create_table('lesson_messages',
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.CheckConstraint("role in ('user', 'assistant')", name=op.f('ck_lesson_messages_role')),
    sa.ForeignKeyConstraint(['slot_id'], ['day_lessons.id'], name=op.f('fk_lesson_messages_slot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', 'position', name=op.f('pk_lesson_messages'))
    )
    op.create_table('mastery_evidence',
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.CheckConstraint('score >= 0 and score <= 1', name=op.f('ck_mastery_evidence_score')),
    sa.ForeignKeyConstraint(['slot_id'], ['day_lessons.id'], name=op.f('fk_mastery_evidence_slot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', 'evidence_id', name=op.f('pk_mastery_evidence'))
    )
    op.create_table('practice_items',
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['day_lessons.id'], name=op.f('fk_practice_items_slot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', 'position', name=op.f('pk_practice_items'))
    )
    op.create_table('quizzes',
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_key', sa.Text(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('best', sa.Integer(), nullable=True),
    sa.Column('draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['day_lessons.id'], name=op.f('fk_quizzes_slot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', name=op.f('pk_quizzes'))
    )
    op.create_table('review_card_removals',
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['day_lessons.id'], name=op.f('fk_review_card_removals_slot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', 'card_id', name=op.f('pk_review_card_removals'))
    )
    op.create_table('review_cards',
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('box', sa.Integer(), nullable=False),
    sa.Column('due', sa.Date(), nullable=False),
    sa.Column('added', sa.Date(), nullable=False),
    sa.Column('last', sa.Date(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('card_topic', sa.Text(), nullable=True),
    sa.Column('card_lesson_no', sa.Integer(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('question', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['day_lessons.id'], name=op.f('fk_review_cards_slot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', 'card_id', name=op.f('pk_review_cards'))
    )
    op.create_index('ix_review_cards_due', 'review_cards', ['due'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('slot_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('from_lesson', sa.Integer(), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mark', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['quizzes.slot_id'], name=op.f('fk_quiz_questions_slot_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', 'position', name=op.f('pk_quiz_questions'))
    )
    # ### end Alembic commands ###

    # the built-in roles and permissions, frozen here (a later change is a new migration)
    roles = sa.table("roles", sa.column("name", sa.Text), sa.column("description", sa.Text),
                     sa.column("builtin", sa.Boolean))
    permissions = sa.table("permissions", sa.column("name", sa.Text), sa.column("description", sa.Text))
    grants = sa.table("role_permissions", sa.column("role", sa.Text), sa.column("permission", sa.Text))
    op.bulk_insert(roles, [{"name": k, "description": v, "builtin": True} for k, v in ROLES.items()])
    op.bulk_insert(permissions, [{"name": k, "description": v} for k, v in PERMISSIONS.items()])
    op.bulk_insert(grants, [{"role": r, "permission": p} for r, ps in GRANTS.items() for p in ps])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_questions')
    op.drop_index('ix_review_cards_due', table_name='review_cards')
    op.drop_table('review_cards')
    op.drop_table('review_card_removals')
    op.drop_table('quizzes')
    op.drop_table('practice_items')
    op.drop_table('mastery_evidence')
    op.drop_table('lesson_messages')
    op.drop_table('lesson_contents')
    op.drop_table('explanations')
    op.drop_table('user_subjects')
    op.drop_table('user_settings')
    op.drop_table('user_roles')
    op.drop_table('usage_events')
    op.drop_table('subject_levels')
    op.drop_index('ix_study_days_user_id_subject', table_name='study_days')
    op.drop_table('study_days')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('role_permissions')
    op.drop_table('reading_books')
    op.drop_table('preferences')
    op.drop_table('learning_signals')
    op.drop_table('invites')
    op.drop_index('ix_identities_user_id', table_name='identities')
    op.drop_table('identities')
    op.drop_table('goals')
    op.drop_index('ix_day_lessons_user_id_subject_lesson_no', table_name='day_lessons')
    op.drop_table('day_lessons')
    op.drop_table('credentials')
    op.drop_index('ix_audit_log_at', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('ai_usage')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
